_welcome:
    path:     /
    defaults: { _controller: FirstUserBundle:Default:index }

login_login_login:
    path:  /login
    defaults: { _controller: FirstUserBundle:Default:login }    

login_login_homepage:
    path:  /dashboard
    defaults: { _controller: FirstUserBundle:Default:welcome }

login_login_signup:
    path:  /signup
    defaults: { _controller: FirstUserBundle:Default:signup }
    
login_login_logout:
    path:  /logout
    defaults: { _controller: FirstUserBundle:Default:logout }

login_login_editaccount:
    path:  /editaccount
    defaults: { _controller: FirstUserBundle:Default:editaccount }

login_login_success:
    path:  /success
    defaults: { _controller: FirstUserBundle:Default:success }    