_welcome:
    path:     /
    defaults: { _controller: FirstUserBundle:Default:index }

login_login_login:
    path:  /login
    defaults: { _controller: FirstUserBundle:Default:login }    

login_login_homepage:
    path:  /dashboard
    defaults: { _controller: FirstUserBundle:Default:welcome }

login_login_signup:
    path:  /signup
    defaults: { _controller: FirstUserBundle:Default:signup }
    
login_login_logout:
    path:  /logout
    defaults: { _controller: FirstUserBundle:Default:logout }

login_login_editaccount:
    path:  /editaccount
    defaults: { _controller: FirstUserBundle:Default:editaccount }
    #requirements:
            #_method: POST

login_login_saveaccount:
    path:  /saveaccount
    defaults: { _controller: FirstUserBundle:Default:saveaccount }
    #requirements:
            #_method: POST            

login_login_editpassword:
    path:  /editpassword
    defaults: { _controller: FirstUserBundle:Default:editpassword }

login_login_savepassword:
    path:  /savepassword
    defaults: { _controller: FirstUserBundle:Default:savepassword }

login_login_resetpassword:
    path:  /resetpassword
    defaults: { _controller: FirstUserBundle:Default:resetpassword }

login_login_updatepassword:
    path:  /updatepassword
    defaults: { _controller: FirstUserBundle:Default:updatepassword } 

login_login_email_link:
    path:  /emaillink
    defaults: { _controller: FirstUserBundle:Default:emaillink }    

login_login_passwordresetted:
    path:  /passwordresetted
    defaults: { _controller: FirstUserBundle:Default:newpassword }

login_login_passwordreviewed:
    path:  /passwordreviewed
    defaults: { _controller: FirstUserBundle:Default:reviewpassword }

login_login_profile:
    path:  /profile
    defaults: { _controller: FirstUserBundle:Default:profile }    