_welcome:
    path:     /
    defaults: { _controller: FirstUserBundle:Default:index }

login_login_homepage:
    pattern:  /dashboard
    defaults: { _controller: FirstUserBundle:Default:welcome }

login_login_signup:
    pattern:  /signup
    defaults: { _controller: FirstUserBundle:Default:signup }
    
login_login_logout:
    pattern:  /logout
    defaults: { _controller: FirstUserBundle:Default:logout }

login_login_editaccount:
    pattern:  /editaccount
    defaults: { _controller: FirstUserBundle:Default:editaccount }

login_login_success:
    pattern:  /success
    defaults: { _controller: FirstUserBundle:Default:success }    