# src/First/Bundle/UserBundle/Resources/config/validation.yml
First\Bundle\UserBundle\Entity\Author:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - Email: ~