parameters:
#    login_login.example.class: First\Bundle\UserBundle\Example

services:
#    login_login.example:
#        class: %login_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]